import type { Locale } from "@/lib/i18n";
import type { Guide, GuideType } from "@/types/guide";

type GuideCopy = {
  title: string; description: string; featured: string; all: string; search: string; area: string;
  empty: string; unavailable: string; duration: string; minutes: string; audience: string;
  stops: string; stay: string; next: string; tip: string; details: string; save: string; saved: string;
  savedTitle: string; login: string; error: string; loading: string; official: string; weather: string; share: string; remove: string; saveHint: string;
  unavailableStop: string; emptyDescription: string; clearFilters: string; explorePlaces: string; types: Record<GuideType, string>;
  weatherTypes: Record<Guide["weather_type"], string>;
};
export const guideCopy: Record<Locale, GuideCopy> = {
  ko: { title: "부산 여행 가이드", description: "부산 여행 전 저장하고 현지에서 따라가는 공식 여행 코스와 실용 가이드.", featured: "추천", all: "전체", search: "가이드 검색", area: "지역", empty: "조건에 맞는 공개 가이드가 없습니다.", unavailable: "가이드를 불러오지 못했습니다. 잠시 후 다시 시도해주세요.", duration: "예상 소요시간", minutes: "분", audience: "추천 대상", stops: "장소", stay: "예상 체류", next: "다음 장소로 이동", tip: "여행 팁", details: "장소 상세 보기", save: "이 코스 저장", saved: "저장됨", savedTitle: "저장한 공식 코스", login: "로그인하고 코스 저장", error: "저장 정보를 처리하지 못했습니다. 다시 시도해주세요.", loading: "불러오는 중…", official: "공식 가이드", weather: "날씨", share: "친구에게 공유", remove: "저장 해제", saveHint: "이 가이드를 저장해 부산에서 다시 확인하세요.", unavailableStop: "일부 장소 정보가 변경되어 이동 안내가 생략될 수 있습니다. 방문 전에 확인해주세요.", emptyDescription: "검색어와 필터를 초기화하거나 공개된 장소 목록에서 다시 찾아보세요.", clearFilters: "필터 초기화", explorePlaces: "장소 둘러보기", types: { AREA: "지역", FOOD: "음식", SITUATION: "상황별", ITINERARY: "여행코스", PRACTICAL: "실용정보" }, weatherTypes: { ANY: "모든 날씨", SUNNY: "맑은 날", RAINY: "비 오는 날", INDOOR: "실내" } },
  zh: { title: "釜山旅行指南", description: "出发前收藏，到釜山后跟着走：官方精选路线、美食与实用旅行指南。", featured: "推荐", all: "全部", search: "搜索旅行指南", area: "地区", empty: "暂无符合条件的公开指南。", unavailable: "暂时无法加载指南，请稍后重试。", duration: "预计用时", minutes: "分钟", audience: "适合人群", stops: "个地点", stay: "建议停留", next: "前往下一站", tip: "旅行提示", details: "查看地点详情", save: "收藏这条路线", saved: "已收藏", savedTitle: "收藏的官方路线", login: "登录并收藏路线", error: "无法更新收藏，请重试。", loading: "加载中…", official: "官方指南", weather: "天气", share: "分享给朋友", remove: "取消收藏", saveHint: "收藏这条路线，到釜山直接照着走。", unavailableStop: "部分地点信息已变更，可能不显示相关交通说明，请出发前确认。", emptyDescription: "可以清除搜索条件，或先查看已公开地点。", clearFilters: "清除筛选", explorePlaces: "浏览地点", types: { AREA: "地区", FOOD: "美食", SITUATION: "主题", ITINERARY: "旅行路线", PRACTICAL: "实用信息" }, weatherTypes: { ANY: "所有天气", SUNNY: "晴天", RAINY: "雨天", INDOOR: "室内" } },
  en: { title: "Busan travel guides", description: "Save official Busan routes and practical guides before your trip, then follow them when you arrive.", featured: "Featured", all: "All", search: "Search guides", area: "Area", empty: "No published guides match your filters.", unavailable: "Guides could not be loaded. Please try again later.", duration: "Estimated duration", minutes: "min", audience: "Recommended for", stops: "places", stay: "Suggested stay", next: "To the next stop", tip: "Travel tip", details: "View place details", save: "Save this course", saved: "Saved", savedTitle: "Saved official courses", login: "Sign in to save", error: "Could not update saved guides. Please try again.", loading: "Loading…", official: "Official guide", weather: "Weather", share: "Share with a friend", remove: "Unsave", saveHint: "Save this guide and reopen it when you are in Busan.", unavailableStop: "Some place information has changed. Related travel instructions may be hidden; check before visiting.", emptyDescription: "Reset the filters or browse published places instead.", clearFilters: "Reset filters", explorePlaces: "Explore places", types: { AREA: "Areas", FOOD: "Food", SITUATION: "Themes", ITINERARY: "Itineraries", PRACTICAL: "Practical" }, weatherTypes: { ANY: "Any weather", SUNNY: "Sunny", RAINY: "Rainy", INDOOR: "Indoors" } },
  ja: { title: "釜山旅行ガイド", description: "旅行前に保存して、釜山に着いたら活用できる公式コースと実用ガイド。", featured: "おすすめ", all: "すべて", search: "ガイドを検索", area: "エリア", empty: "条件に合う公開ガイドはありません。", unavailable: "ガイドを読み込めませんでした。後でもう一度お試しください。", duration: "所要時間の目安", minutes: "分", audience: "おすすめの方", stops: "スポット", stay: "滞在時間の目安", next: "次のスポットへ", tip: "旅のヒント", details: "スポットの詳細", save: "このコースを保存", saved: "保存済み", savedTitle: "保存した公式コース", login: "ログインして保存", error: "保存情報を更新できませんでした。もう一度お試しください。", loading: "読み込み中…", official: "公式ガイド", weather: "天気", share: "友だちに共有", remove: "保存解除", saveHint: "このガイドを保存して、釜山でまた確認できます。", unavailableStop: "一部のスポット情報が変更され、関連する移動案内が省略される場合があります。訪問前にご確認ください。", emptyDescription: "条件をリセットするか、公開中のスポットを確認してください。", clearFilters: "条件をリセット", explorePlaces: "スポットを見る", types: { AREA: "エリア", FOOD: "グルメ", SITUATION: "テーマ別", ITINERARY: "旅行コース", PRACTICAL: "実用情報" }, weatherTypes: { ANY: "すべての天気", SUNNY: "晴れの日", RAINY: "雨の日", INDOOR: "屋内" } },
};
export function guideContent(guide: Guide, locale: Locale) {
  return { title: guide[`title_${locale}`], description: guide[`description_${locale}`] };
}
