begin;

alter table public.place_submissions
  add column if not exists duplicate_key text;

alter table public.place_submissions
  drop constraint if exists place_submissions_duplicate_key_format_check,
  add constraint place_submissions_duplicate_key_format_check
    check (duplicate_key is null or duplicate_key ~ '^[0-9a-f]{64}$');

create unique index if not exists place_submissions_active_duplicate_key_uidx
on public.place_submissions(duplicate_key)
where duplicate_key is not null and status in ('pending', 'reviewing');

alter table public.places
  drop constraint if exists places_price_range_order_check,
  add constraint places_price_range_order_check
    check (price_min is null or price_max is null or price_min <= price_max) not valid,
  drop constraint if exists places_food_price_min_sanity_check,
  add constraint places_food_price_min_sanity_check
    check (category not in ('restaurant', 'cafe', 'bar') or price_min is null or price_min = 0 or price_min >= 1000) not valid,
  drop constraint if exists places_food_price_max_sanity_check,
  add constraint places_food_price_max_sanity_check
    check (category not in ('restaurant', 'cafe', 'bar') or price_max is null or price_max = 0 or price_max >= 1000) not valid;

alter table public.place_menu_items
  drop constraint if exists place_menu_items_price_check,
  add constraint place_menu_items_price_check
    check (price is null or price = 0 or price >= 1000) not valid;

comment on column public.place_submissions.duplicate_key is
  'SHA-256 fingerprint used only to reject duplicate pending/reviewing submissions. Generated by the application from a normalized map URL or name+location.';

commit;

notify pgrst, 'reload schema';
